export const REQUESTED_GIFT = 'REQUESTED_GIFT';
export const FILTERED_BY_CATEGORY = 'FILTERED_BY_CATEGORY';
export const FILTER_BY_FORM = 'FILTER_BY_FORM';
export const RENDER_RANDOM = 'RENDER_RANDOM';
export const SEARCH = 'SEARCH';
export const SAVE_TO_LOCALSTORAGE = 'SAVE_TO_LOCALSTORAGE';
